CREATE USER medicai_user WITH PASSWORD 'medicai_password';
CREATE DATABASE medicai_db;

GRANT CONNECT ON DATABASE medicai_db TO medicai_user;
GRANT USAGE ON SCHEMA public TO medicai_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO medicai_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO medicai_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO medicai_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO medicai_user;