"""create conversation table

Revision ID: 49562c6134f1
Revises: 94ccc25d8ed1
Create Date: 2024-08-21 22:41:18.591759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49562c6134f1'
down_revision = '94ccc25d8ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('conversationId', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation')
    # ### end Alembic commands ###
