"""create new table healthRecord

Revision ID: c430e22b4615
Revises: f019c8f0c634
Create Date: 2024-07-29 23:46:17.628274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c430e22b4615'
down_revision = 'f019c8f0c634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('isHeadache', sa.Boolean(), nullable=True),
    sa.Column('isCancer', sa.Boolean(), nullable=True),
    sa.Column('isDiabetes', sa.Boolean(), nullable=True),
    sa.Column('isBloodClots', sa.Boolean(), nullable=True),
    sa.Column('isArthritis', sa.Boolean(), nullable=True),
    sa.Column('isAbnormalSkinConditions', sa.Boolean(), nullable=True),
    sa.Column('isHighOrLowBloodPressure', sa.Boolean(), nullable=True),
    sa.Column('isFibromyalgia', sa.Boolean(), nullable=True),
    sa.Column('isNeckOrBackPain', sa.Boolean(), nullable=True),
    sa.Column('isNumbness', sa.Boolean(), nullable=True),
    sa.Column('isVaricoseVeins', sa.Boolean(), nullable=True),
    sa.Column('isRecentInjury', sa.Boolean(), nullable=True),
    sa.Column('isNursingOrPregnant', sa.Boolean(), nullable=True),
    sa.Column('isDepression', sa.Boolean(), nullable=True),
    sa.Column('isFatigue', sa.Boolean(), nullable=True),
    sa.Column('isInsomnia', sa.Boolean(), nullable=True),
    sa.Column('isHavingHeartDisease', sa.Boolean(), nullable=True),
    sa.Column('isHavingSurgery', sa.Boolean(), nullable=True),
    sa.Column('isHavingChronisIllness', sa.Boolean(), nullable=True),
    sa.Column('isHavingHighOrLowBloodPressure', sa.Boolean(), nullable=True),
    sa.Column('isHavingAllergies', sa.Boolean(), nullable=True),
    sa.Column('isTakingMedication', sa.Boolean(), nullable=True),
    sa.Column('allergies', sa.String(length=150), nullable=True),
    sa.Column('medications', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('health_record')
    # ### end Alembic commands ###
